name: myanimelist_api
version: 0.1.1
description: API wrapper for MyAnimeList
repository: https://github.com/rsktg/MyAnimeList-API
dependencies:
  json_annotation: ^3.1.1
  http: ^0.12.2
dev_dependencies:
  effective_dart: ^1.3.0
  json_serializable: ^3.5.1
  build_runner: ^1.11.0
  test: ^1.15.7
environment:
  sdk: '>=2.2.0 <3.0.0'
