name: myanimelist_api
version: 0.3.0
description: Asynchronous API wrapper for the official MyAnimeList API v2.
repository: https://github.com/rsktg/MyAnimeList-API
dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.1
dev_dependencies:
  build_runner: ^2.0.3
  coverage: ^1.0.2
  effective_dart: ^1.3.1
  json_serializable: ^4.1.2
  pedantic: ^1.11.0
  test: ^1.17.4
  very_good_analysis: ^2.0.3
environment:
  sdk: '>=2.12.0 <3.0.0'
