name: myanimelist_api
version: 0.2.0+1
description: Asynchronous API wrapper for the official MyAnimeList API v2.
repository: https://github.com/rsktg/MyAnimeList-API
dependencies:
  json_annotation: ^3.1.1
  http: ^0.12.2
dev_dependencies:
  effective_dart: ^1.3.0
  json_serializable: ^3.5.1
  build_runner: ^1.11.1
  test: ^1.15.7
environment:
  sdk: '>=2.3.0 <3.0.0'
